version: "3.3"
services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db1
      - MYSQL_USER=u1
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"  
